name: 'Sentry CLI action test'
description: 'Sentry CLI hello world test'
inputs:
  sentry_msg:
    description: 'Event to send to Sentry'
    required: true
  working_directory:
    description: 'Directory to collect sentry release information from. Useful when collecting information from a non-standard checkout directory.'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install Sentry CLI
      run: yarn add --dev --no-lockfile @sentry/cli@2
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Sending event from node script
      env:
        INPUT_SENTRY_MSG: ${{ inputs.sentry_msg }}
        INPUT_WORKING_DIRECTORY: ${{ inputs.working_directory }}
      run: yarn start
      working-directory: ${{ github.action_path }}
      shell: bash
