name: 'Sentry CLI action test'
description: 'Sentry CLI hello world test'
inputs:
  sentry_msg:
    description: 'Event to send to Sentry'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      shell: bash

    - uses: actions/cache@v4
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Set cache hit var
      run: echo "CACHE_HIT=${{ steps.yarn-cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install Sentry CLI
      run: yarn add @sentry/cli
      working-directory: ${{ github.action_path }}
      shell: bash

    - name: Sending event from node script
      env:
        INPUT_SENTRY_MSG: ${{ inputs.sentry_msg }};
      run: node dist/index.js
      working-directory: ${{ github.action_path }}
      shell: bash
