  # Releases always publish a `v[major].[minor].[patch]` tag
  # This action creates/updates `v[major]` and `v[major].[minor]` tags
  name: Create release tags
  on:
    release:
      types: [released]

  permissions:
    contents: write

  jobs:
    create-tags:
      runs-on: ubuntu-latest
      steps:
        - run: |
            echo "TAG: ${{ github.event.release.tag_name }}"
          
        - uses: actions/checkout@v4
          with:
            ref: ${{ github.event.release.tag_name }}

        - name: Set git user to getsentry-bot
          run: |
            echo "GIT_COMMITTER_NAME=andreiborza" >> $GITHUB_ENV;
            echo "GIT_AUTHOR_NAME=andreiborza" >> $GITHUB_ENV;
            echo "EMAIL=andrei.borza@sentry.io" >> $GITHUB_ENV;

        - name: Extract major and minor versions
          run: |
            echo "MAJOR_VERSION=$(echo '${{ github.event.release.tag_name }}' | cut -d. -f1)" >> $GITHUB_ENV;
            echo "MINOR_VERSION=$(echo '${{ github.event.release.tag_name }}' | cut -d. -f1-2)" >> $GITHUB_ENV;

        - name: Create and push major and minor tags
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git tag -f ${{ env.MAJOR_VERSION }}
            git push -f origin ${{ env.MAJOR_VERSION }}
            git tag -f ${{ env.MINOR_VERSION }}
            git push -f origin ${{ env.MINOR_VERSION }}
          shell: bash
