name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-action:
    name: Test GitHub Action
    runs-on: ubuntu-latest

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: test-action
        name: Test action
        uses: ./
        env:
          SENTRY_DSN: "https://7e1cfdae24e683dd79e0723b80ba28d8@o447951.ingest.us.sentry.io/4508733014736896"
        with:
          sentry_msg: Message from CI tests
