name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - name: Parse version from tag
        id: version
        uses: release-kit/semver@v2

      - name: Use parsed version
        run: |
          echo "${{ steps.version.outputs.major }}"
          echo "${{ steps.version.outputs.minor }}"
          echo "${{ steps.version.outputs.patch }}"
          echo "${{ steps.version.outputs.prerelease }}"
          echo "${{ steps.version.outputs.build }}"
          echo "${{ steps.version.outputs.full }}"

  test_matrix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: test-action
        name: Test action
        uses: ./
        env:
          SENTRY_DSN: "https://7e1cfdae24e683dd79e0723b80ba28d8@o447951.ingest.us.sentry.io/4508733014736896"
        with:
          sentry_msg: Message from ${{ matrix.os }} CI test
