name: Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  semver:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        uses: actions/checkout@v4

      - name: Extract versions
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          echo "full_version=$TAG" >> $GITHUB_ENV
          echo "major=$(echo $TAG | cut -d. -f1)" >> $GITHUB_ENV
          echo "minor=$(echo $TAG | cut -d. -f1-2)" >> $GITHUB_ENV
        shell: bash

      - run: |
          echo "$full_version"
          echo "$major"
          echo "$minor"

  test_matrix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}

    steps:
      - id: checkout
        uses: actions/checkout@v4

      - id: test-action
        name: Test action
        uses: ./
        env:
          SENTRY_DSN: "https://7e1cfdae24e683dd79e0723b80ba28d8@o447951.ingest.us.sentry.io/4508733014736896"
        with:
          sentry_msg: Message from ${{ matrix.os }} CI test
